[project]
name = "recipe-agent"
version = "0.0.1"
description = "Conversational recipe suggestion agent using Ollama."
authors = [
    { name = "Hai Huang" }
]
license = { text = "Apache" }
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk[http-server]>=0.2.16",
    "openai>=1.0.0",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.30.0",
    "opentelemetry-exporter-otlp",
]

[project.scripts]
server = "recipe_agent.agent:run"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
